import { type AlphabetNotationOptions } from "../types/plugin";
import { SuffixNotationBase } from "./SuffixNotationBase";

/**
 * Converts a tier number to a multi-character suffix using an ordered symbol set.
 *
 * This is the raw algorithm behind {@link AlphabetNotation}, exposed as a standalone
 * function for cases where you need suffix generation without the full notation plugin
 * (e.g. column headers, label generators, custom renderers).
 *
 * The algorithm is base-N positional with no leading-symbol ambiguity:
 * - Tier 0 -> `""` (no suffix)
 * - Tier 1 -> `alphabet[0]`
 * - Tier N -> `alphabet[N-1]` (last single-character suffix)
 * - Tier N+1 -> `alphabet[0]+alphabet[0]` (first two-character suffix)
 *
 * This matches Excel column naming when `alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"`.
 *
 * @param tier - The tier number (`Math.floor(exponent / 3)` in notation context). Must be >= 0.
 * @param alphabet - The ordered symbol set. Defaults to `"abcdefghijklmnopqrstuvwxyz"`.
 * @returns The suffix string, or `""` for tier 0.
 *
 * @example
 * alphabetSuffix(0, "abc")   // ""
 * alphabetSuffix(1, "abc")   // "a"
 * alphabetSuffix(3, "abc")   // "c"
 * alphabetSuffix(4, "abc")   // "aa"
 * alphabetSuffix(6, "abc")   // "ac"
 * alphabetSuffix(7, "abc")   // "ba"
 *
 * // Excel columns
 * alphabetSuffix(1, "ABCDEFGHIJKLMNOPQRSTUVWXYZ")  // "A"
 * alphabetSuffix(26, "ABCDEFGHIJKLMNOPQRSTUVWXYZ") // "Z"
 * alphabetSuffix(27, "ABCDEFGHIJKLMNOPQRSTUVWXYZ") // "AA"
 */
export function alphabetSuffix(tier: number, alphabet = "abcdefghijklmnopqrstuvwxyz"): string {
    if (alphabet.length === 0) throw new Error("alphabet must not be empty");
    if (tier <= 0) return "";

    const index = tier - 1; // tier 1 = first symbol = index 0

    // Find which length group this index falls in.
    let length = 1;
    let capacity = alphabet.length;
    let offset = 0;

    while (index >= offset + capacity) {
        offset += capacity;
        length++;
        capacity = alphabet.length ** length;
    }

    let remaining = index - offset;
    const chars = new Array<string>(length);

    for (let i = length - 1; i >= 0; i--) {
        chars[i] = alphabet[remaining % alphabet.length]!;
        remaining = Math.floor(remaining / alphabet.length);
    }

    return chars.join("");
}

/**
 * Formats numbers using multi-character suffixes derived from a configurable symbol set
 * (e.g. `"1.50a"`, `"3.20b"`, `"1.00aa"`).
 *
 * The suffix sequence is generated by {@link alphabetSuffix}: tier 1 -> first symbol,
 * tier N -> last symbol, tier N+1 -> first two-symbol combination, and so on.
 *
 * Pass a custom `alphabet` to produce any suffix sequence - lowercase letters (default),
 * uppercase (Excel-style columns), Greek letters, emoji, or any ordered set of strings.
 *
 * @example
 * // Default: lowercase a-z
 * letterNotation.format(1.5, 3, 2);  // "1.50a"
 * letterNotation.format(1.5, 78, 2); // "1.50z"
 * letterNotation.format(1.5, 81, 2); // "1.50aa"
 *
 * @example
 * // Excel-style columns
 * const excelNotation = new AlphabetNotation({ alphabet: "ABCDEFGHIJKLMNOPQRSTUVWXYZ" });
 * excelNotation.format(1.5, 3, 2);   // "1.50A"
 * excelNotation.format(1.5, 78, 2);  // "1.50Z"
 * excelNotation.format(1.5, 81, 2);  // "1.50AA"
 */
export class AlphabetNotation extends SuffixNotationBase {
    private readonly defaultSuffix = "";
    private readonly alphabet: string;
    private readonly suffixCache = new Map<number, string>();

    /**
     * @param options - Plugin options. `alphabet` defaults to `"abcdefghijklmnopqrstuvwxyz"`.
     *   `separator` defaults to `""` (no space between the number and suffix).
     */
    public constructor(options: AlphabetNotationOptions = {}) {
        super(options);
        this.alphabet = options.alphabet ?? "abcdefghijklmnopqrstuvwxyz";
    }

    /**
     * Returns the suffix label for the given tier.
     *
     * Tier 0 returns `""` - no suffix for values below 10^3.
     * Tier 1 -> first alphabet symbol, tier N -> last, tier N+1 -> first two-symbol combination.
     *
     * Results are cached after the first call per tier.
     *
     * @param tier - The exponent tier (`floor(exponent / 3)`), >= 0.
     * @returns The suffix string, or `""` for tier 0.
     */
    public override getSuffix(tier: number): string {
        if (tier === 0) {
            return this.defaultSuffix;
        }

        const cached = this.suffixCache.get(tier);
        if (cached !== undefined) return cached;

        const result = alphabetSuffix(tier, this.alphabet);
        this.suffixCache.set(tier, result);
        return result;
    }
}

/** Pre-built {@link AlphabetNotation} instance using lowercase `a-z` with no separator. */
export const letterNotation = new AlphabetNotation();
